\chapterfont{\color{white}}

# The Wave Function

\vspace{-12cm}

\begin{center}
    \begin{tikzpicture}
        \draw[white] (10,5) circle (0.01);
        \draw[DarkOrchid,fill=DarkOrchid] (0,0) rectangle (18.2,0.2);
        \draw[DarkOrchid,fill=DarkOrchid] (6,1.8) rectangle (18.2,0.2);
        \node[white] at (12.1,1) {\Huge{\textsc{The Wave Function}}};
        \node at (3,1) {\Large{\textsc{Chapter 14}}};
    \end{tikzpicture}
\end{center}

In this chapter, the sums and differences of *equal-angled* trigonometric operations will be explored.

\[\text{e.g. }3\sin{x}\degree+4\cos{x}\degree\]

The graphs of basic trigonometric functions such as $y=3\sin{x}\degree$ and $y=4\cos{x}\degree$ should be familiar:

\begin{center}
    \begin{tikzpicture}
        \draw[-stealth] (0,0) -- (14,0) node[below] {$x$};
        \draw[-stealth] (0,-3) -- (0,3) node[left] {$y$};
        \draw[smooth,domain=0:2*3.141592,xscale=2] plot (\x,{0.5*3*sin(\x r)});
        \draw[smooth,domain=0:2*3.141592,xscale=2] plot (\x,{0.5*4*cos(\x r)});
        \node[above] at (4*3.141592,0) {$360\degree$};
        \foreach \y in {-5,-4,...,5}{
        \draw (0,0.5*\y) -- (-0.1,0.5*\y) node[left] {\y};
}
        \node[below] at (3.5*3.141592,-1.35) {$y=3\sin{x}\degree$};
        \node[above] at (4*3.141592,2) {$y=4\cos{x}\degree$};
    \end{tikzpicture}
\end{center}

The graph of $\color{DarkOrchid}y=3\sin{x}\degree+4\cos{x}\degree$ is the same as that of $\color{DarkOrchid}y=5\cos{(x-36.9)}\degree$.

\begin{center}
    \begin{tikzpicture}
        \draw[-stealth] (0,0) -- (14,0) node[below] {$x$};
        \draw[-stealth] (0,-3) -- (0,3) node[left] {$y$};
        \draw[black!50,smooth,domain=0:2*3.141592,xscale=2] plot (\x,{0.5*3*sin(\x r)});
        \draw[black!50,smooth,domain=0:2*3.141592,xscale=2] plot (\x,{0.5*4*cos(\x r)});
        \draw[smooth,very thick,DarkOrchid,domain=0:2*3.141592,xscale=2] plot (\x,{0.5*4*cos(\x r)+0.5*3*sin(\x r)});
        \node[above] at (4*3.141592,0) {$360\degree$};
        \foreach \y in {-5,-4,...,5}{
        \draw (0,0.5*\y) -- (-0.1,0.5*\y) node[left] {\y};
}
        \node[black!50,below] at (3.5*3.141592,-1.35) {$y=3\sin{x}\degree$};
        \node[black!50,above] at (4*3.141592,2) {$y=4\cos{x}\degree$};
        \node[above,DarkOrchid] at (1.3*3.141592,2.5) {$y=3\sin{x}\degree+4\cos{x}\degree=5\cos{(x-36.9)}\degree$};
        \draw[dashed,DarkOrchid] (2*0.644,2.5) -- (2*0.644,0) node[below] {$36.9\degree$};
    \end{tikzpicture}
\end{center}

Determining that $3\sin{x}\degree+4\cos{x}\degree=5\cos{(x-36.9)}\degree$ allows the maximum values and minimum values of $3\sin{x}\degree+4\cos{x}\degree$ to be determined and the values of $x$ which produce them, and allow equations such as $3\sin{x}\degree+4\cos{x}\degree=2$ to be solved.

*Any* trigonometric expression $k_1\sin{x}\pm k_2\cos{x}$ can be written as either $k\sin{(x\pm a)}$ or $k\cos{(x\pm a)}$.

This chapter will cover how to do this and explore the various applications of this property.

\pagebreak

## The Wave Function using $k\cos{(x-a)}$

\vspace{-0.5cm}

Whilst any of $k\sin{(x\pm a)}$ or $k\cos{(x\pm a)}$ may be used in general, any Higher exam question is likely to specify a particular form to use. The simplest is often $k\cos{(x-a)}$.

To express $3\sin{x}\degree+4\cos{x}\degree$ in the form $k\cos{(x-a)}\degree$, two key *trigonometric identities* are needed:

\[\sin^2{x}+\cos^2{x}=1\hspace{2cm}\text{and}\hspace{2cm}\tan{x}=\frac{\sin{x}}{\cos{x}}\]

First, $k\cos{(x-a)}\degree$ can be expanded using the the formula $\cos{(A\pm B)}=\cos{A}\cos{B}\mp \sin{A}\sin{B}$:

\[k\cos{(x-a)}\degree=k\cos{x}\degree\cos{a}\degree+k\sin{x}\degree\sin{a}\degree\]

It is required that this expansion is equal to the original expression:

\[3\underline{\sin{x}\degree}+4\doubleunderline{\cos{x}\degree}=k\doubleunderline{\cos{x}\degree}\cos{a}\degree+k\underline{\sin{x}\degree}\sin{a}\degree\]

Equating the coefficients of $\underline{\sin{x}\degree}$ and $\doubleunderline{\cos{x}\degree}$ gives a set of simultaneous equations in $k$ and $a$:

\begin{align*}
    k\sin{a}\degree&=3&&\color{DarkOrchid}\longleftarrow \text{Coefficients of }\underline{\sin{x}\degree}\\
    k\cos{a}\degree&=4&&\color{DarkOrchid}\longleftarrow \text{Coefficients of }\doubleunderline{\cos{x}\degree}
\end{align*}

Squaring both sides of each equation and adding allows $k$ to be determined using $\sin^2{x}+\cos^2{x}=1$:

\begin{align*}
    k^2\sin^2{a}\degree+k^2\cos^2{a}\degree&=3^2+4^2\\
    k^2\left(\sin^2{x}\degree+\cos^2{x}\degree\right)&=3^2+4^2\\
    k^2(1)&=3^2+4^2\\
    \color{DarkOrchid}k&\color{DarkOrchid}=\sqrt{3^2+4^2}\\
    k&=\sqrt{25}\\
    k&=5
\end{align*}

Dividing $k\sin{a}\degree$ by $k\cos{a}\degree$ allows $a$ to be calculated, noting $k\sin{a}\degree$ and $k\cos{a}\degree$ are both positive:

\vspace{2.8cm}
\hspace{14cm}
\begin{tikzpicture}[remember picture, overlay, scale=0.5]
        \draw (-1.5,0) -- (1.5,0);
        \draw (0,-1) -- (0,1);
        \node at (0.7,0.5) {A};
        \node at (-0.7,0.5) {S};
        \node at (-0.7,-0.5) {T};
        \node at (0.7,-0.5) {C};
        \node[DarkOrchid,above right] at (0.7,0.65) {\scriptsize{$a\degree$}};
        \node[DarkOrchid,right] at (0.7,0.5) {\ding{51}\ding{51}};
        \node[DarkOrchid,left] at (-0.7,0.5) {\ding{51}};
        \node[DarkOrchid,right] at (0.7,-0.5) {\ding{51}};
\end{tikzpicture}

\vspace{-3.8cm}
\begin{align*}
    \color{DarkOrchid}\frac{k\sin{a}\degree}{k\cos{a}\degree}&\color{DarkOrchid}=\frac{3}{4}\\
    \tan{a}\degree&=\frac{3}{4}\\
    a\degree_{\text{acute}}&=\tan^{-1}{\left(\frac{3}{4}\right)}=36.9\degree\\
    a\degree&=36.9\degree
\end{align*}

Hence $3\sin{x}\degree+4\cos{x}\degree=5\cos{(x-36.9)}\degree$. Here it has been assumed that $k>0$ and $0<a<360$.

\pagebreak

Some abbreviations of the working shown on the previous page are routinely permitted in the Higher exam. The following example demonstrates an appropriate level of detail in its solution.

\begin{tcolorbox}[title=Example,colback=DarkOrchid!1!, colframe=DarkOrchid]

Express $3\cos{x}-\sin{x}$ in the form $k\cos{(x-a)}$ where $k>0$ and $0<a<2\pi$.

\tcblower

\vspace{10cm}
\hspace{2.2cm}
\begin{tikzpicture}[remember picture, overlay, scale=0.5]
        \draw[white] (-8,0) -- (8,0);
        \draw (-1.5,0) -- (1.5,0);
        \draw (0,-1) -- (0,1);
        \node at (0.7,0.5) {A};
        \node at (-0.7,0.5) {S};
        \node at (-0.7,-0.5) {T};
        \node at (0.7,-0.5) {C};
        \node[DarkOrchid,below right] at (0.7,-0.65) {\scriptsize{$360\degree-\text{acute}\degree$}};
        \node[DarkOrchid,right] at (0.7,-0.5) {\ding{51}\ding{51}};
        \node[DarkOrchid,right] at (0.7,0.5) {\ding{51}};
        \node[DarkOrchid,left] at (-0.7,-0.5) {\ding{51}};
\end{tikzpicture}

\vspace{-4cm}
\hspace{8cm}
\begin{tikzpicture}[remember picture, overlay]
        \draw[thick,DarkOrchid,-stealth] (160:8) arc (160:200:8);
\end{tikzpicture}

\vspace{-7.5cm}
\begin{align*}
    3\cos{x}-\sin{x}&=k\cos{(x-a)}&&\\[0.5em]
    3\doubleunderline{\cos{x}}-\underline{\sin{x}}&=k\doubleunderline{\cos{x}}\cos{a}+k\underline{\sin{x}}\sin{a}&&\color{DarkOrchid}\longleftarrow \text{Expand }k\cos{(x-a)}\\[1.5em]
    k\sin{a}&=-1&&\color{DarkOrchid}\longleftarrow \text{Equate }\sin{x}\text{ coefficients}\\[0.5em]
    k\cos{a}&=3&&\color{DarkOrchid}\longleftarrow \text{Equate }\cos{x}\text{ coefficients}\\[1.5em]
    k&=\sqrt{(-1)^2+3^2}&&\color{DarkOrchid}\longleftarrow \text{Calculate }k\\[0.5em]
    &=\sqrt{10}\\[1em]
    \tan{a}&=\frac{-1}{3}&&\color{DarkOrchid}\longleftarrow \text{Find }\tan{a}\\[0.5em]
    \text{acute}\degree&=\tan^{-1}{\left(\frac{1}{3}\right)}=18.4\degree &&\color{DarkOrchid}\longleftarrow \text{Find acute angle first}\\[1.5em]
    &&&\color{DarkOrchid}\longleftarrow \text{Negative }\sin{a}\text{: quadrants T and C}\\[0.5em]
    &&&\color{DarkOrchid}\longleftarrow \text{Positive }\cos{a}\text{: quadrants A and C}\\[2em]
    a\degree &=341.6\degree&&\color{DarkOrchid}\longleftarrow \text{Using }360\degree-18.4\degree\text{ (Double-ticked quadrant)}\\[0.5em]
    a &=5.96&&\color{DarkOrchid}\longleftarrow \text{Convert to radians: }341.6\times\frac{\pi}{180}\\[1.5em]
    3\cos{x}-\sin{x}&=\sqrt{10}\cos{(x-5.96)}&&\color{DarkOrchid}\longleftarrow \text{State solution}
\end{align*}

\end{tcolorbox}

\vspace{-0.5cm}

#### Exercise 14.1 {-}

\vspace{-0.3cm}

\begin{enumerate}
    \item Express each of the following in the form $k\cos{(x-a)}\degree$, where $k>0$ and $0<a<360$. \faCalculator
    \vspace{-0.2cm}
    \begin{enumerate}
        \begin{multicols}{3}
            \item $5\cos{x}\degree+12\sin{x}\degree$
            \item $4\sin{x}\degree+5\cos{x}\degree$
            \item $6\cos{x}\degree+\sin{x}\degree$
        \end{multicols}
    \end{enumerate}
    \item Express each of the following in the form $k\cos{(x-a)}$, where $k>0$ and $0<a<2\pi$. \faCalculator
    \vspace{-0.2cm}
    \begin{enumerate}
        \begin{multicols}{3}
            \item $8\sin{x}-6\cos{x}$
            \item $\cos{x}-3\sin{x}$
            \item $-2\sin{x}-\cos{x}$
        \end{multicols}
    \end{enumerate}
    \item Express each of the following in the form $k\cos{(x-a)}\degree$, where $k>0$ and $0<a<360$.
    \vspace{-0.2cm}
    \begin{enumerate}
        \begin{multicols}{3}
            \item $\sin{x}\degree+\cos{x}\degree$
            \item $\cos{x}\degree-\sqrt{3}\sin{x}\degree$
            \item $-\sin{x}\degree-\sqrt{3}\cos{x}\degree$
        \end{multicols}
    \end{enumerate}
\end{enumerate}

\pagebreak

## Other Forms of the The Wave Function

\vspace{-0.5cm}

As well as $k\cos{(x-a)}$, three other forms may be used, shown below including their expansions:

\vspace{-1.0cm}

\begin{align*}
    k\cos{(x+a)}&\color{DarkOrchid}=k\cos{x}\cos{a}-k\sin{x}\sin{a}\\
    k\sin{(x+a)}&\color{DarkOrchid}=k\sin{x}\cos{a}+k\sin{x}\cos{a}\\
    k\sin{(x-a)}&\color{DarkOrchid}=k\sin{x}\cos{a}-k\sin{x}\cos{a}
\end{align*}

\vspace{-0.3cm}

\begin{tcolorbox}[title=Example,colback=DarkOrchid!1!, colframe=DarkOrchid]

Express $12\cos{x}\degree-5\sin{x}\degree$ in the form $k\sin{(x-a)}\degree$ where $k>0$ and $0<a<360$.

\tcblower

\vspace{9.7cm}
\hspace{3.2cm}
\begin{tikzpicture}[remember picture, overlay, scale=0.5]
        \draw[white] (-8,0) -- (8,0);
        \draw (-1.5,0) -- (1.5,0);
        \draw (0,-1) -- (0,1);
        \node at (0.7,0.5) {A};
        \node at (-0.7,0.5) {S};
        \node at (-0.7,-0.5) {T};
        \node at (0.7,-0.5) {C};
        \node[DarkOrchid,below left] at (-0.7,-0.65) {\scriptsize{$180\degree+\text{acute}\degree$}};
        \node[DarkOrchid,left] at (-0.7,-0.5) {\ding{51}\ding{51}};
        \node[DarkOrchid,right] at (0.7,-0.5) {\ding{51}};
        \node[DarkOrchid,left] at (-0.7,0.5) {\ding{51}};
\end{tikzpicture}

\vspace{-3.7cm}
\hspace{8.5cm}
\begin{tikzpicture}[remember picture, overlay]
        \draw[thick,DarkOrchid,-stealth] (160:8) arc (160:200:8);
\end{tikzpicture}

\vspace{-7.5cm}
\begin{align*}
    12\cos{x}\degree-5\sin{x}\degree&=k\sin{(x-a)}\degree&&\\[0.5em]
    12\doubleunderline{\cos{x}\degree}-5\underline{\sin{x}\degree}&=k\underline{\sin{x}\degree}\cos{a}\degree-k\doubleunderline{\cos{x}\degree}\sin{a}\degree&&\color{DarkOrchid}\longleftarrow \text{Expand }k\sin{(x-a)}\degree\\[1.5em]
    -k\sin{a}\degree&=12\implies k\sin{a}\degree=-12&&\color{DarkOrchid}\longleftarrow \text{Equate }\sin{x}\degree\text{ coefficients}\\[0.5em]
    k\cos{a}\degree&=-5&&\color{DarkOrchid}\longleftarrow \text{Equate }\cos{x}\degree\text{ coefficients}\\[1.5em]
    k&=\sqrt{(-12)^2+(-5)^2}&&\color{DarkOrchid}\longleftarrow \text{Calculate }k\\[0.5em]
    &=13\\[1.5em]
    \tan{a}\degree&=\frac{-12}{-5}=\frac{12}{5}&&\color{DarkOrchid}\longleftarrow \text{Find }\tan{a}\degree\\[0.5em]
    \text{acute}\degree&=\tan^{-1}{\left(\frac{12}{5}\right)}=67.4\degree &&\color{DarkOrchid}\longleftarrow \text{Find acute angle first}\\[0.8em]
    &&&\color{DarkOrchid}\longleftarrow \text{Negative }\sin{a}\degree\text{: quadrants T and C}\\[0.5em]
    &&&\color{DarkOrchid}\longleftarrow \text{Negative }\cos{a}\degree\text{: quadrants S and T}\\[1.5em]
    a\degree &=247.4\degree&&\color{DarkOrchid}\longleftarrow \text{Using }180\degree+67.4\degree\text{ (Double-ticked)}\\[1em]
    12\cos{x}\degree-5\sin{x}\degree&=13\sin{(x-247.4)}\degree&&\color{DarkOrchid}\longleftarrow \text{State solution}
\end{align*}

\end{tcolorbox}

\vspace{-0.5cm}

#### Exercise 14.2 {-}

\vspace{-0.3cm}

\begin{enumerate}
    \item Express each of the following in the form $k\sin{(x+a)}\degree$, where $k>0$ and $0<a<360$. \faCalculator
    \vspace{-0.2cm}
    \begin{enumerate}
        \begin{multicols}{3}
            \item $3\cos{x}\degree+2\sin{x}\degree$
            \item $4\sin{x}\degree+3\cos{x}\degree$
            \item $7\cos{x}\degree-\sin{x}\degree$
        \end{multicols}
    \end{enumerate}
    \item Express each of the following in the form $k\cos{(x+a)}$, where $k>0$ and $0<a<2\pi$. \faCalculator
    \vspace{-0.2cm}
    \begin{enumerate}
        \begin{multicols}{3}
            \item $3\sin{x}+8\cos{x}$
            \item $-3\cos{x}-4\sin{x}$
            \item $-6\sin{x}+2\cos{x}$
        \end{multicols}
    \end{enumerate}
    \item Express each of the following in the form $k\sin{(x-a)}$, where $k>0$ and $0<a<2\pi$.
    \vspace{-0.2cm}
    \begin{enumerate}
        \begin{multicols}{3}
            \item $\sqrt{3}\sin{x}+\cos{x}$
            \item $\cos{x}-\sin{x}$
            \item $2\sqrt{3}\sin{x}-2\cos{x}$
        \end{multicols}
    \end{enumerate}
\end{enumerate}

\pagebreak

## Maximum and Minimum Values using the Wave Function

\vspace{-0.5cm}

The graphs of $y=\sin{x}\degree$ and $y=\cos{x}\degree$, including their turning points, should already be familiar:

\begin{multicols}{2}
    \begin{center}
        \begin{tikzpicture}
            \draw[-stealth] (0,0) -- (7,0) node[below] {$x$};
            \draw[-stealth] (0,-1.4) -- (0,1.4) node[left] {$y$};
            \draw[smooth,domain=0:2*3.141592] plot (\x,{sin(\x r)});
            \node[above] at (2*3.141592,0) {$360$};
            \node[left] at (0,1) {$1$};
            \node[left] at (0,0) {$0$};
            \node[left] at (0,-1) {$-1$};
            \node at (3.3,1) {$y=\sin{x}\degree$};
            \foreach \x in {0.5,1,1.5,2}{
            \draw (3.141592*\x,0) -- (3.141592*\x,-0.1);
}
        \end{tikzpicture}
    \end{center}
    \begin{center}
        \begin{tikzpicture}
            \draw[-stealth] (0,0) -- (7,0) node[below] {$x$};
            \draw[-stealth] (0,-1.4) -- (0,1.4) node[left] {$y$};
            \draw[smooth,domain=0:2*3.141592] plot (\x,{cos(\x r)});
            \node[below] at (2*3.141592,0) {$360$};
            \node[left] at (0,1) {$1$};
            \node[left] at (0,0) {$0$};
            \node[left] at (0,-1) {$-1$};
            \node at (3.3,1) {$y=\cos{x}\degree$};
            \draw[dashed] (2*3.141592,1) -- (2*3.141592,0);
            \foreach \x in {0.5,1,1.5,2}{
            \draw (3.141592*\x,0) -- (3.141592*\x,-0.1);
}
        \end{tikzpicture}
    \end{center}
\end{multicols}

Graphs of the form $k\sin{(x\pm a)}$ and $k\cos{(x\pm a)}$ have maximum/minimum values of $\pm k$, and their *horizontal translation* is described by $\pm a$ following the rules covered in the Graph Transformations chapter.

\begin{tcolorbox}[title=Example,colback=DarkOrchid!1!, colframe=DarkOrchid]

Given that $3\sin{x}\degree+4\cos{x}\degree$ can be expressed as $5\cos{(x-36.9)}\degree$, state the minimum value of $f(x)=3\sin{x}\degree+4\cos{x}\degree$ and the value of $x$ at which it occurs for $0<x<360$.

\tcblower

\textcolor{DarkOrchid}{Sketch the graph of $y=5\cos{x}\degree$ translated $36.9\degree$ to the right:}

\begin{center}
        \begin{tikzpicture}
            \draw[-stealth] (0,0) -- (7,0) node[below] {$x$};
            \draw[-stealth] (0,-1.6) -- (0,2) node[left] {$y$};
            \draw[thin,black!50,smooth,domain=0:2*3.141592] plot (\x,{0.3*5*cos(\x r)});
            \draw[thick,DarkOrchid,smooth,domain=0:2*3.141592] plot (\x,{0.3*3*sin(\x r)+0.3*4*cos(\x r)});
            \draw[thick,dashed,DarkOrchid,smooth,domain=2*3.141592:6.9272] plot (\x,{0.3*3*sin(\x r)+0.3*4*cos(\x r)});
            \node[black!50] at (2*3.141592,1.8) {$y=5\cos{x}\degree$};
            \node[right,DarkOrchid] at (6.9272,1.5) {$y=5\cos{(x-36.9)}\degree$};
            \node[below] at (2*3.141592,0) {$360$};
            \node[below] at (3.141592,0) {$180$};
            \node[left] at (0,1.5) {$5$};
            \node[left] at (0,0) {$0$};
            \node[left] at (0,-1.5) {$-5$};
            \node at (3.3,1) {$y=\cos{x}\degree$};
            \draw[dashed,black!50] (2*3.141592,1) -- (2*3.141592,0);
            \foreach \x in {0.5,1,1.5,2}{
            \draw (3.141592*\x,0) -- (3.141592*\x,-0.1);
}
            \draw[stealth-,DarkOrchid] (3.8859,-1.6) -- (4.1859,-1.9) node[right] {$(216.9\degree,-5)$};
            \draw[stealth-,black!50] (3.041592,-1.6) -- (2.741592,-1.9) node[left] {$(180\degree,-5)$};
            \draw[DarkOrchid,fill=DarkOrchid] (3.7859,-1.5) circle (0.05);
            \draw[black!50,fill=black!50] (3.141592,-1.5) circle (0.05);
        \end{tikzpicture}
    \end{center}

\textcolor{DarkOrchid}{Use the graph to state the answer:}

\vspace{0.1cm}

Hence the minimum value of $f(x)$ is $-5$, which occurs when $x=216.9$.

\end{tcolorbox}

\vspace{-0.5cm}

#### Exercise 14.3 {-}

\vspace{-0.3cm}

\begin{enumerate}
    \item Sketch each for $0<x<360$, showing the coordinates of any roots and turning points:
    \vspace{-0.2cm}
    \begin{enumerate}
        \begin{multicols}{3}
            \item $7\cos{(x-10)}\degree$
            \item $3\sin{(x-20)}\degree$
            \item $\sqrt{5}\cos{(x+40)}\degree$
        \end{multicols}
    \end{enumerate}
    \item Find the maximum value of each and the value(s) of $x$ for which they occur for $0<x<360$:
    \vspace{-0.2cm}
    \begin{enumerate}
        \begin{multicols}{3}
            \item $8\sin{(x-50)}\degree$
            \item $\sqrt{2}\cos{(x+27)}\degree$
            \item $7\sin{(x+42.3)}\degree$
        \end{multicols}
    \end{enumerate}
    \item Find the minimum value of each and the value(s) of $x$ for which they occur for $0<x<2\pi$:
    \vspace{-0.2cm}
    \begin{enumerate}
        \begin{multicols}{3}
            \item $3\cos{\left(x-\dfrac{\pi}{6}\right)}$
            \item $5\sin{\left(x+\dfrac{\pi}{3}\right)}+2$
            \item $-12\sin{\left(x+\dfrac{\pi}{4}\right)}$
        \end{multicols}
    \end{enumerate}
    \item
    \begin{enumerate}
        \item Express $6\sin{x}\degree-7\cos{x}\degree$ in the form $k\sin{(x-a)}\degree$ where $k>0$ and $0<a<360$. \faCalculator
        \item Hence state the coordinates of the turning points of $12\sin{x}\degree-14\cos{x}\degree$ for $0<x<360$.
    \end{enumerate}
\end{enumerate}

\pagebreak

## Solving Equations using the Wave Function

\vspace{-0.5cm}

Solving an equation like $3\sin{x}\degree+4\cos{x}\degree=2$ can be approached by using the wave function to rewrite it as $5\cos{(x-36.9)}\degree=2$, before solving it in the manner covered in Chapter 6.

\begin{tcolorbox}[title=Example,colback=DarkOrchid!1!, colframe=DarkOrchid]

It can be shown that $5\sin{x}\degree-2\cos{x}\degree$ can be expressed as $\sqrt{29}\sin{(x-21.8)}\degree$.

Hence, solve the equation $5\sin{x}\degree-2\cos{x}\degree=4$ where $0<x<360$.

\tcblower

\vspace{5.6cm}
\hspace{7cm}
\begin{tikzpicture}[remember picture, overlay, scale=0.5]
        \draw[white] (-8,0) -- (8,0);
        \draw (-1.5,0) -- (1.5,0);
        \draw (0,-1) -- (0,1);
        \node at (0.7,0.5) {A};
        \node at (-0.7,0.5) {S};
        \node at (-0.7,-0.5) {T};
        \node at (0.7,-0.5) {C};
        \node[DarkOrchid,above right] at (0.7,0.65) {\scriptsize{$a\degree$}};
        \node[DarkOrchid,above left] at (-0.7,0.65) {\scriptsize{$180\degree-a\degree$}};
        \node[DarkOrchid,right] at (0.7,0.5) {\ding{51}};
        \node[DarkOrchid,left] at (-0.7,0.5) {\ding{51}};
\end{tikzpicture}

\vspace{-6.6cm}
\begin{align*}
    5\sin{x}\degree-2\cos{x}\degree&=4&&\\[0.5em]
    \sqrt{29}\sin{(x-21.8)}\degree&=4&&\color{DarkOrchid}\longleftarrow \text{Substitute the wave function form}\\[0.5em]
    \sin{(x-21.8)}\degree&=\frac{4}{\sqrt{29}}&&\color{DarkOrchid}\longleftarrow \text{Rearrange to }\sin{(\dots)}=\dots\\[0.5em]
    \color{DarkOrchid}a&\color{DarkOrchid}=\sin^{-1}{\left(\frac{4}{\sqrt{29}}\right)=48.0\degree}&&\color{DarkOrchid}\longleftarrow \text{Calculate acute angle}\\[2.5em]
    &&&\color{DarkOrchid}\longleftarrow \text{Positive }\sin{a}\degree\text{: quadrants A and S}\\[2.5em]
    x-21.8\degree&=48.0\degree,180\degree-48.0\degree&&\color{DarkOrchid}\longleftarrow \text{Apply ticked quadrants}\\[0.5em]
    x-21.8\degree&=48.0\degree,132.0\degree&&\\[0.5em]
    x\degree&=69.8\degree,153.8\degree&&\color{DarkOrchid}\longleftarrow \text{Add }21.8\degree\text{ to both sides}
\end{align*}

\end{tcolorbox}

Note that any solutions outwith the domain (often $0<x<360$) should have $360\degree$ added or subtracted to bring it back within the domain, where possible.

\vspace{-0.5cm}

#### Exercise 14.4 {-}

\vspace{-0.3cm}

\begin{enumerate}
    \item Solve each equation for $0<x<360$: \faCalculator
    \begin{enumerate}
        \begin{multicols}{3}
            \item $7\sin{(x-18)}\degree=4$
            \item $3\cos{(x+34.1)}\degree=-2$
            \item $\sqrt{5}\sin{(x-106)}\degree+1=0$
        \end{multicols}
    \end{enumerate}
    \item Given $6\sin{x}\degree-8\cos{x}\degree=10\sin{(x-53.1)}\degree$, solve $6\sin{x}\degree-8\cos{x}\degree=5$ where $0<x<360$.
    \item 
    \begin{enumerate}
        \item Express $\sqrt{3}\sin{x}\degree+\cos{x}\degree$ in the form $k\sin{(x-a)}\degree$ where $k>0$ and $0<a<360$. 
        \item Hence solve the equation $\sqrt{3}\sin{x}\degree+\cos{x}\degree=1$ where $0<x<360$.
    \end{enumerate}
    \item Solve each equation for $0<x<2\pi$: \faCalculator
    \begin{enumerate}
        \begin{multicols}{3}
            \item $4\sin{(x+0.31)}+2=1$
            \item $9\cos{(x+1.24)}=5$
            \item $2\sqrt{3}\sin{(x-0.82)}=\sqrt{5}$
        \end{multicols}
    \end{enumerate}
    \item 
    \begin{enumerate}
        \item Express $3\cos{x}+2\c{sinx}$ in the form $k\cos{(x+a)}$ where $k>0$ and $0<a<2\pi$. \faCalculator
        \item Hence solve the equation $2+6\sin{x}+4\cos{x}=5$ where $0<x<2\pi$. \faCalculator
    \end{enumerate}
\end{enumerate}

\pagebreak

## Multiple Angles and Different Variables

\vspace{-0.5cm}

The techniques covered in this chapter can be applied to trigonometric expressions beyond those containing only $\sin{x}$ and $\cos{x}$; they work for any sum or difference of *equal-angled* trigonometric operations.

\vspace{-0.2cm}

\[\text{e.g. }\qquad 3\sin{t}\degree+4\cos{t}\degree \qquad \text{ or } \qquad 2\sin{2x}-5\cos{2x}\]

\begin{tcolorbox}[title=Example,colback=DarkOrchid!1!, colframe=DarkOrchid]

Express $5\cos{2t}\degree-3\sin{2t}\degree$ in the form $k\sin{(2t+a)}\degree$ where $k>0$ and $0<a<360$.

\tcblower

\vspace{10cm}
\hspace{4cm}
\begin{tikzpicture}[remember picture, overlay, scale=0.5]
        \draw[white] (-8,0) -- (8,0);
        \draw (-1.5,0) -- (1.5,0);
        \draw (0,-1) -- (0,1);
        \node at (0.7,0.5) {A};
        \node at (-0.7,0.5) {S};
        \node at (-0.7,-0.5) {T};
        \node at (0.7,-0.5) {C};
        \node[DarkOrchid,above left] at (-0.7,0.65) {\scriptsize{$180\degree-\text{acute}\degree$}};
        \node[DarkOrchid,left] at (-0.7,0.5) {\ding{51}\ding{51}};
        \node[DarkOrchid,right] at (0.7,0.5) {\ding{51}};
        \node[DarkOrchid,left] at (-0.7,-0.5) {\ding{51}};
\end{tikzpicture}

\vspace{-4cm}
\hspace{8.3cm}
\begin{tikzpicture}[remember picture, overlay]
        \draw[thick,DarkOrchid,-stealth] (160:8) arc (160:200:8);
\end{tikzpicture}

\vspace{-7.6cm}
\begin{align*}
    5\cos{2t}\degree-3\sin{2t}\degree&=k\sin{(2t+a)}\degree&&\\[0.5em]
    5\doubleunderline{\cos{2t}\degree}-3\underline{\sin{2t}\degree}&=k\underline{\sin{2t}\degree}\cos{a}\degree+k\doubleunderline{\cos{2t}\degree}\sin{a}\degree&&\color{DarkOrchid}\longleftarrow \text{Expand }k\sin{(2t+a)}\degree\\[1.5em]
    k\sin{a}\degree&=5&&\color{DarkOrchid}\longleftarrow \text{Equate }\sin{2t}\degree\text{ coefficients}\\[0.5em]
    k\cos{a}\degree&=-3&&\color{DarkOrchid}\longleftarrow \text{Equate }\cos{2t}\degree\text{ coefficients}\\[1.5em]
    k&=\sqrt{(5)^2+(-3)^2}&&\color{DarkOrchid}\longleftarrow \text{Calculate }k\\[0.5em]
    &=\sqrt{34}\\[1.5em]
    \tan{a}\degree&=\frac{5}{-3}=-\frac{5}{3}&&\color{DarkOrchid}\longleftarrow \text{Find }\tan{a}\degree\\[0.5em]
    \text{acute}\degree&=\tan^{-1}{\left(\frac{5}{3}\right)}=59.0\degree &&\color{DarkOrchid}\longleftarrow \text{Find acute angle first}\\[0.8em]
    &&&\color{DarkOrchid}\longleftarrow \text{Positive }\sin{a}\degree\text{: quadrants A and S}\\[0.5em]
    &&&\color{DarkOrchid}\longleftarrow \text{Negative }\cos{a}\degree\text{: quadrants S and T}\\[1.5em]
    a\degree &=121.0\degree&&\color{DarkOrchid}\longleftarrow \text{Using }180\degree-59.0\degree\text{ (Double-ticked)}\\[1em]
    5\cos{2t}\degree-3\sin{2t}\degree&=\sqrt{34}\sin{(2t+121.0)}\degree&&\color{DarkOrchid}\longleftarrow \text{State solution}
\end{align*}

\end{tcolorbox}

\vspace{-0.5cm}

#### Exercise 14.5 {-}

\vspace{-0.3cm}

\begin{enumerate}
    \item Express $4\cos{t}\degree-3\sin{t}\degree$ in the form $k\sin{(t-a)}\degree$, where $k>0$ and $0<a<360$. \faCalculator
    \item Express $2\sin{2x}-\cos{2x}$ in the form $k\cos{(2x-a)}$ where $k>0$ and $0<a<2\pi$. \faCalculator
    \item 
    \begin{enumerate}
        \item Express $12\cos{t}\degree+5\sin{t}\degree$ in the form $k\sin{(t+a)}\degree$, where $k>0$ and $0<a<360$. \faCalculator
        \item Hence state:
        \begin{enumerate}
            \item The maximum value of the function $f(x)=12\cos{t}\degree+5\sin{t}\degree$, $0<t<360$.
            \item The value(s) of $t$ for which it occurs.
        \end{enumerate}
    \end{enumerate}
    \item 
    \begin{enumerate}
        \item Express $\sin{2x}-\sqrt{3}\cos{2x}$ in the form $k\cos{(2x-a)}$ where $k>0$, $0<a<2\pi$.
        \item Hence solve $\sin{2x}-\sqrt{3}\cos{2x}-1=0$, $0<x<2\pi$.
        \item Sketch $y=-\sin{2x}+\sqrt{3}\cos{2x}-1=0$ for $0\leqslant x \leqslant 2\pi$.
    \end{enumerate}
\end{enumerate}

\pagebreak

## Wave Function Review Exercise {-}

\begin{enumerate}
    \item Express $8\sin{x}\degree+7\cos{x}\degree$ in the form $k\sin{(x-a)}\degree$ where $k>0$ and $0<a<360$. \faCalculator\\[0.5em]
    \item Express $\sqrt{5}\sin{x}+\cos{x}$ in the form $k\cos{(x-a)}$ where $k>0$ and $0<a<2\pi$. \faCalculator\\[0.5em]
    \item Express $\sqrt{3}\cos{t}\degree-\sin{t}\degree$ in the form $k\sin{(t+a)}\degree$ where $k>0$ and $0<a<360$.\\[0.5em]
    \item Part of the graphs of $y=3\cos{x}\degree-5\sin{x}\degree$ and $y=-4$ are shown in the diagram below: \faCalculator
    \begin{center}
        \begin{tikzpicture}[scale=1.5]
            \draw[-stealth] (-0.5,0) -- (7.5,0) node[below] {$x$};
            \draw[-stealth] (0,-1.5) -- (0,1.5) node[left] {$y$};
            \node[below left] {O};
            \draw[thick,smooth,domain=0:2*3.141592] plot (\x,{0.6*cos(\x r)-1.0*sin(\x r)}) node[right] {$y=3\cos{x}\degree-5\sin{x}\degree$};
            \draw[dashed] (2*3.141592,0.6) -- (2*3.141592,0) node[below] {$360\degree$};
            \draw[thick] (0,-0.8) -- (2*3.141592,-0.8) node[right] {$y=-4$};
            \draw[fill] (1.29639,-0.8) circle (0.04) node[below left] {P};
            \draw[fill] (2.92604,-0.8) circle (0.04) node[below right] {Q};
        \end{tikzpicture}
    \end{center}
    Points P and Q are points of intersection.\\
    \begin{enumerate}
        \item Express $y=3\cos{x}\degree-5\sin{x}\degree$ in the form $k\cos{(x+a)}\degree$ where $k>0$ and $0<a<360$.\\[0.1em]
        \item Hence determine the coordinates of P and Q.\\[0.5em]
    \end{enumerate}
    \item 
    \begin{enumerate}
        \item Express $2\sin{x}\degree-4\cos{x}\degree$ in the form $k\sin{(x-a)}\degree$ where $k>0$ and $0<x<360$. \faCalculator\\[0.1em]
        \item Hence sketch the graph of $y=2\sin{x}\degree-4\cos{x}\degree$ for $0<x<360$.\\[0.5em]
    \end{enumerate}
    \item 
    \begin{enumerate}
        \item Express $\cos{x}+\sqrt{3}\sin{x}$ in the form $k\cos{(x-a)}$ where $k>0$ and $0<a<2\pi$.\\[0.1em]
        \item Hence sketch the graph of $y=2\cos{x}+2\sqrt{3}\sin{x}$ for $0<x<2\pi$.\\[0.5em]
    \end{enumerate}
    \item 
    \begin{enumerate}
        \item Express $6\cos{t}-3\sin{t}$ in the form $k\cos{(t+a)}$ where $k>0$ and $0<a<2\pi$. \faCalculator\\[0.1em]
        \item Hence solve $2\cos{t}-\sin{t}+2=1$ where $0<t<2\pi$. \faCalculator\\[0.5em]
    \end{enumerate}
    \item 
    \begin{enumerate}
        \item Express $\sin{2x}\degree-\cos{2x}\degree$ in the form $k\sin{(2x-a)}$ where $k>0$ and $0<a<360$.\\[0.1em]
        \item Hence solve the equation $\sin{2x}\degree=\cos{2x}\degree$ where $0<x<360$.
    \end{enumerate}
\end{enumerate}

\pagebreak
