\chapterfont{\color{white}}

# Trig Equations

\vspace{-12cm}
\begin{center}
\begin{tikzpicture}
\draw[white] (10,5) circle (0.01);
\draw[DarkOrchid,fill=DarkOrchid] (0,0) rectangle (18.2,0.2);
\draw[DarkOrchid,fill=DarkOrchid] (6,1.8) rectangle (18.2,0.2);
\node[white] at (12.1,1) {\Huge{\textsc{Trig Equations}}};
\node at (3,1) {\Large{\textsc{Chapter 23}}};
\end{tikzpicture}
\end{center}

Different types of equations (such as *quadratic* or *linear*) require different methods in order to solve them. 

*Trigonometric equations* are those which include $\sin{x\degree}$, $\cos{x\degree}$ or $\tan{x\degree}$. Since these are some of the more complicated operations encountered so far, the best way to begin thinking about how trig equations may be solved is to consider a *graphical* interpretation:

\vspace{-0.8cm}

\begin{align*}
\color{DarkOrchid}\text{Equation:}&\quad \sin{x\degree}=0.5\\[0.5em]
\color{DarkOrchid}\text{Interpretation:}&\quad \textit{``For which value(s) of }x\textit{ is the graph }y=\sin{x}\textit{ at a height of }0.5\textit{?''}
\end{align*}

\vspace{-0.3cm}

Plotting the graph of $y=\sin{x\degree}$ and marking the points at which its height is $0.5$ reveals that, between $0\degree$ and $360\degree$, there are **two solutions**:  

\begin{center}
    \begin{tikzpicture}[xscale=0.04,yscale=3]
        \foreach \x in {30,60,...,360}{
        \draw[black!30] (\x,-1) -- (\x,1);
        }
        \foreach \y in {-1,-0.9,...,1}{
        \draw[black!30] (-0.1,\y) -- (360,\y);
        }
        \draw[black!30] (0,1) -- (360,1);
        \draw[-stealth] (0,0) -- (400,0) node[below] {$x\degree$};
        \draw[-stealth] (0,-1.1) -- (0,1.2) node[left] {$y$};
        \foreach \x in {0,30,...,360}{
        \draw (\x,0) -- (\x,-0.01);
        }
        \foreach \x in {90,180,270,360}{
        \node[below] at (\x,0) {\x \degree};
        }
        \node[left] at (0,1) {1};
        \node[left] at (0,0.5) {0.5};
        \node[left] at (0,0) {0};
        \node[left] at (0,-0.5) {-0.5};
        \node[left] at (0,-1) {-1};
        \draw[thick,DarkOrchid,smooth,domain=0:360] plot (\x,{sin(\x)});
        \node[DarkOrchid,above] at (90,1) {$y=\sin{x}\degree$};
        \draw[DarkOrchid,dashed] (30,0.5) -- (30,0) node[below] {$30\degree$};
        \draw[DarkOrchid,dashed] (150,0.5) -- (150,0) node[below] {$150\degree$};
        \draw[fill,DarkOrchid] (30,0.5) ellipse (3 and 0.04);
        \draw[fill,DarkOrchid] (150,0.5) ellipse (3 and 0.04);
    \end{tikzpicture}
\end{center}

Hence the solutions to the equation $\sin{x\degree}=0.5$ where $0<x<360$ are $\color{DarkOrchid}x\degree=30\degree$ and $\color{DarkOrchid}x\degree=150\degree$.

Note that $\sin^{-1}(0.5)$ gives the *acute* solution $30\degree$, and $180\degree-30\degree=150\degree$ using the graph's symmetry.

The same above graph can similarly be used to solve a number of equations in $\sin{x\degree}$:

\vspace{-0.8cm}

\begin{align*}
\color{DarkOrchid}\text{Equation:}&\quad \sin{x\degree}=-1\\[0.5em]
\color{DarkOrchid}\text{Interpretation:}&\quad \textit{``For which value(s) of }x\textit{ is the graph }y=\sin{x}\textit{ at a height of }-1\textit{?''}\\[0.5em]
\color{DarkOrchid}\text{Solution:}&\quad x\degree=270\degree
\end{align*}

\vspace{-0.3cm}

The graph also reveals that equations of the form $\sin{x\degree}=k$ only have solutions for $-1\leqslant k \leqslant 1$:

\vspace{-0.8cm}

\begin{align*}
\color{DarkOrchid}\text{Equation:}&\quad \sin{x\degree}=2\\[0.5em]
\color{DarkOrchid}\text{Interpretation:}&\quad \textit{``For which value(s) of }x\textit{ is the graph }y=\sin{x}\textit{ at a height of }2\textit{?''}\\[0.5em]
\color{DarkOrchid}\text{Solution:}&\quad \textbf{No solutions.}
\end{align*}

\vspace{-0.3cm}

This chapter will introduce a method for solving trig equations without a graph, and explore contexts in which the ability to solve trig equations may be useful in the real world.

\pagebreak

## Solving Trig Equations Graphically

\vspace{-0.5cm}

When considering $\sin{x\degree}=0.4$, calculating $\sin^{-1}(0.4)$ gives the \textcolor{DarkOrchid}{\textbf{acute angle}} $23.6\degree$ (to 1 decimal place).

This acute angle and the symmetries of $y=\sin{x\degree}$ allow $\sin{x\degree}=0.4$ and $\sin{x\degree}=-0.4$ to be solved:

\vspace{-0.7cm}

\begin{center}
    \begin{tikzpicture}[xscale=0.04,yscale=1.6]
        \draw[-stealth] (0,0) -- (380,0) node[below] {$x\degree$};
        \draw[-stealth] (0,-1.1) -- (0,1.2) node[above] {$y$};
        \foreach \x in {0,30,...,360}{
        \draw (\x,0) -- (\x,-0.01);
        }
        \foreach \x in {90,180,270,360}{
        \node[below] at (\x,0) {\small{\x \degree}};
        }
        \node[left] at (0,1) {1};
        \node[left] at (0,0.4) {0.4};
        \node[left] at (0,0) {0};
        \node[left] at (0,-0.4) {-0.4};
        \node[left] at (0,-1) {-1};
        \draw[very thick,DarkOrchid,smooth,domain=0:360] plot (\x,{sin(\x)});
        \node[DarkOrchid,above right] at (360,0) {$y=\sin{x}\degree$};
        \draw[DarkOrchid,dashed] (23.6,0.4) -- (23.6,0) node[below] {$23.6\degree$};
        \draw[DarkOrchid,dashed] (156.4,0.4) -- (156.4,0) node[below] {$156.4\degree$};
        \draw[DarkOrchid,dashed] (203.6,-0.4) -- (203.6,0);
        \node[above,DarkOrchid] at (203.6,0) {$203.6\degree$};
        \node[above,DarkOrchid] at (336.4,0) {$336.4\degree$};
        \draw[DarkOrchid,dashed] (336.4,-0.40) -- (336.4,0);
        \draw[fill,DarkOrchid] (23.6,0.4) ellipse (1.75 and 0.032);
        \draw[fill,DarkOrchid] (156.4,0.4) ellipse (1.75 and 0.032);
        \draw[fill,DarkOrchid] (180+23.6,-0.4) ellipse (1.75 and 0.032);
        \draw[fill,DarkOrchid] (360-23.6,-0.4) ellipse (1.75 and 0.032);
        \draw (90,-1) -- (90,1);
        \draw (180,-1) -- (180,1);
        \draw (270,-1) -- (270,1);
        \draw (360,-1) -- (360,1);
        \draw[thick,DarkOrchid,-stealth] (2,0.4) -- (16.4,0.4);
        \draw[thick,DarkOrchid,stealth-] (163.4,0.4) -- (178,0.4);
        \draw[thick,DarkOrchid,-stealth] (182,-0.4) -- (196.6,-0.4);
        \draw[thick,DarkOrchid,stealth-] (343.4,-0.4) -- (358,-0.4);
        \node[above] at (45,1) {1st quadrant};
        \node[above,DarkOrchid] at (45,1.3) {$23.6\degree$};
        \node[above] at (135,1) {2nd quadrant};
        \node[above,DarkOrchid] at (135,1.3) {$180\degree-23.6\degree$};
        \node[above] at (225,1) {3rd quadrant};
        \node[above,DarkOrchid] at (225,1.3) {$180\degree+23.6\degree$};
        \node[above] at (315,1) {4th quadrant};
        \node[above,DarkOrchid] at (315,1.3) {$360\degree-23.6\degree$};
    \end{tikzpicture}
\end{center}

\vspace{-1.3cm}

\begin{multicols}{2}

\begin{align*}
\text{\color{DarkOrchid}Equation:}\hspace{0.2cm} \sin{x\degree}&=0.4\\[0.1em]
\text{\color{DarkOrchid}Solutions:}\hspace{0.8cm} x\degree&=23.6\degree,156.4\degree
\end{align*}

\vfill\null

\columnbreak

\begin{align*}
\text{\color{DarkOrchid}Equation:}\hspace{0.2cm} \sin{x\degree}&=-0.4\\[0.1em]
\text{\color{DarkOrchid}Solutions:}\hspace{0.75cm} x\degree&=203.6\degree,336.4\degree
\end{align*}

\vfill\null

\end{multicols}

\vspace{-1cm}

Similarly, $\cos{x\degree}=0.7$ and $\cos{x\degree}=-0.7$ can be solved using \textcolor{DarkOrchid}{\textbf{acute angle}} $\cos^{-1}(0.7)=45.6\degree$ (1dp):

\vspace{-0.7cm}

\begin{center}
    \begin{tikzpicture}[xscale=0.04,yscale=1.6]
        \draw[-stealth] (0,0) -- (380,0) node[below] {$x\degree$};
        \draw[-stealth] (0,-1.1) -- (0,1.2) node[above] {$y$};
        \foreach \x in {0,30,...,360}{
        \draw (\x,0) -- (\x,-0.01);
        }
        \foreach \x in {90,180,270,360}{
        \node[below] at (\x,0) {\small{\x \degree}};
        }
        \node[left] at (0,1) {1};
        \node[left] at (0,0.7) {0.7};
        \node[left] at (0,0) {0};
        \node[left] at (0,-0.7) {-0.7};
        \node[left] at (0,-1) {-1};
        \draw[very thick,DarkOrchid,smooth,domain=0:360] plot (\x,{cos(\x)});
        \node[DarkOrchid,right] at (360,1) {$y=\cos{x}\degree$};
        \draw[DarkOrchid,dashed] (45.6,0.7) -- (45.6,0) node[below] {$45.6\degree$};
        \draw[DarkOrchid,dashed] (314.4,0.7) -- (314.4,0) node[below] {$314.4\degree$};
        \draw[DarkOrchid,dashed] (134.4,-0.7) -- (134.4,0);
        \node[above,DarkOrchid] at (134.6,0) {$134.6\degree$};
        \node[above,DarkOrchid] at (222.6,0) {$222.6\degree$};
        \draw[DarkOrchid,dashed] (222.6,-0.7) -- (222.6,0);
        \draw[fill,DarkOrchid] (45.6,0.7) ellipse (1.75 and 0.032);
        \draw[fill,DarkOrchid] (314.4,0.7) ellipse (1.75 and 0.032);
        \draw[fill,DarkOrchid] (180+45.6,-0.7) ellipse (1.75 and 0.032);
        \draw[fill,DarkOrchid] (180-45.6,-0.7) ellipse (1.75 and 0.032);
        \draw (90,-1) -- (90,1);
        \draw (180,-1) -- (180,1);
        \draw (270,-1) -- (270,1);
        \draw (360,-1) -- (360,1);
        \draw[thick,DarkOrchid,-stealth] (2,0.7) -- (37.6,0.7);
        \draw[thick,DarkOrchid,stealth-] (142.4,-0.7) -- (178,-0.7);
        \draw[thick,DarkOrchid,-stealth] (182,-0.7) -- (217.6,-0.7);
        \draw[thick,DarkOrchid,stealth-] (322.4,0.7) -- (358,0.7);
        \node[above] at (45,1) {1st quadrant};
        \node[above,DarkOrchid] at (45,1.3) {$45.6\degree$};
        \node[above] at (135,1) {2nd quadrant};
        \node[above,DarkOrchid] at (135,1.3) {$180\degree-45.6\degree$};
        \node[above] at (225,1) {3rd quadrant};
        \node[above,DarkOrchid] at (225,1.3) {$180\degree+45.6\degree$};
        \node[above] at (315,1) {4th quadrant};
        \node[above,DarkOrchid] at (315,1.3) {$360\degree-45.6\degree$};
    \end{tikzpicture}
\end{center}

\vspace{-1.3cm}

\begin{multicols}{2}

\begin{align*}
\text{\color{DarkOrchid}Equation:}\hspace{0.2cm} \cos{x\degree}&=0.7\\[0.1em]
\text{\color{DarkOrchid}Solutions:}\hspace{0.8cm} x\degree&=45.6\degree,314.4\degree
\end{align*}

\vfill\null

\columnbreak

\begin{align*}
\text{\color{DarkOrchid}Equation:}\hspace{0.2cm} \cos{x\degree}&=-0.7\\[0.1em]
\text{\color{DarkOrchid}Solutions:}\hspace{0.75cm} x\degree&=134.4\degree,225.6\degree
\end{align*}

\vfill\null

\end{multicols}

\vspace{-1cm}

To solve $\tan{x\degree}=1.3$ and $\tan{x\degree}=-1.3$, again the \textcolor{DarkOrchid}{\textbf{acute angle}} $\tan^{-1}(1.3)=52.4\degree$ (1dp) is helpful:

\vspace{-0.7cm}

\begin{center}
    \begin{tikzpicture}[xscale=0.04,yscale=0.4]
        \draw[-stealth] (0,0) -- (380,0) node[below] {$x\degree$};
        \draw[-stealth] (0,-4) -- (0,4.8) node[above] {$y$};
        \foreach \x in {0,30,...,360}{
        \draw (\x,0) -- (\x,-0.01);
        }
        \foreach \x in {90,180,270,360}{
        \node[below] at (\x,0) {\small{\x \degree}};
        }
        \node[left] at (0,4) {4};
        \node[left] at (0,1.3) {1.3};
        \node[left] at (0,0) {0};
        \node[left] at (0,-1.3) {-1.3};
        \node[left] at (0,-4) {-4};
        \draw[very thick,DarkOrchid,smooth,domain=0:75] plot (\x,{tan(\x)});
        \draw[very thick,DarkOrchid,smooth,domain=105:255] plot (\x,{tan(\x)});
        \draw[very thick,DarkOrchid,smooth,domain=285:360] plot (\x,{tan(\x)});
        \node[DarkOrchid,right] at (360,1) {$y=\tan{x}\degree$};
        \draw[DarkOrchid,dashed] (52.4,1.3) -- (52.4,0) node[below] {$52.4\degree$};
        \draw[DarkOrchid,dashed] (307.6,-1.3) -- (307.6,0) node[above] {$307.6\degree$};
        \draw[DarkOrchid,dashed] (127.6,-1.3) -- (127.6,0);
        \node[above,DarkOrchid] at (127.6,0) {$127.6\degree$};
        \node[below,DarkOrchid] at (232.4,0) {$232.6\degree$};
        \draw[DarkOrchid,dashed] (232.4,-1.3) -- (232.4,0);
        \draw[fill,DarkOrchid] (52.4,1.3) ellipse (1.75 and 4*0.032);
        \draw[fill,DarkOrchid] (307.6,-1.3) ellipse (1.75 and 4*0.032);
        \draw[fill,DarkOrchid] (180+52.4,1.3) ellipse (1.75 and 4*0.032);
        \draw[fill,DarkOrchid] (180-52.4,-1.3) ellipse (1.75 and 4*0.032);
        \draw (90,-4) -- (90,4);
        \draw (180,-4) -- (180,4);
        \draw (270,-4) -- (270,4);
        \draw (360,-4) -- (360,4);
        \draw[thick,DarkOrchid,-stealth] (2,1.3) -- (42.6,1.3);
        \draw[thick,DarkOrchid,stealth-] (137.4,-1.3) -- (178,-1.3);
        \draw[thick,DarkOrchid,-stealth] (182,1.3) -- (222.6,1.3);
        \draw[thick,DarkOrchid,stealth-] (317.4,-1.3) -- (358,-1.3);
        \node[above] at (45,4) {1st quadrant};
        \node[above,DarkOrchid] at (45,4*1.3) {$52.4\degree$};
        \node[above] at (135,4) {2nd quadrant};
        \node[above,DarkOrchid] at (135,4*1.3) {$180\degree-52.4\degree$};
        \node[above] at (225,4) {3rd quadrant};
        \node[above,DarkOrchid] at (225,4*1.3) {$180\degree+52.4\degree$};
        \node[above] at (315,4) {4th quadrant};
        \node[above,DarkOrchid] at (315,4*1.3) {$360\degree-52.4\degree$};
    \end{tikzpicture}
\end{center}

\vspace{-1.3cm}

\begin{multicols}{2}

\begin{align*}
\text{\color{DarkOrchid}Equation:}\hspace{0.2cm} \tan{x\degree}&=1.3\\[0.1em]
\text{\color{DarkOrchid}Solutions:}\hspace{0.8cm} x\degree&=52.4\degree,232.4\degree
\end{align*}

\vfill\null

\columnbreak

\begin{align*}
\text{\color{DarkOrchid}Equation:}\hspace{0.2cm} \tan{x\degree}&=-1.3\\[0.1em]
\text{\color{DarkOrchid}Solutions:}\hspace{0.75cm} x\degree&=127.6\degree,307.6\degree
\end{align*}

\vfill\null

\end{multicols}

\vspace{-1cm}

\pagebreak

### Exercise 23.1 {-}

\begin{enumerate}
    \item Use the graph of $y=\sin{x\degree}$ below to solve the following equations for $0\leqslant x \leqslant 360$.
    \begin{center}
    \begin{tikzpicture}[xscale=0.025,yscale=2]
        \draw[-stealth] (0,0) -- (380,0) node[right] {$x$};
        \draw[-stealth] (0,-1) -- (0,1.2) node[above] {$y$};
        \foreach \x in {0,30,...,360}{
        \draw (\x,0) -- (\x,-0.01);
        }
        \foreach \x in {90,180,270,360}{
        \node[below] at (\x,0) {$\small{\x}$};
        }
        \node[left] at (0,1) {1};
        \node[left] at (0,0.6) {0.6};
        \node[left] at (0,0) {0};
        \node[left] at (0,-1) {-1};
        \node[below] at (36.9,0) {$36.9$};
        \draw[thick,smooth,domain=0:360] plot (\x,{sin(\x)});
        \node[above] at (90,1) {$y=\sin{x}\degree$};
        \draw[dashed] (0,0.6) -- (36.9,0.6) -- (36.9,0);
        \draw[fill] (36.9,0.6) ellipse (1.5 and 0.01875);
        \node[below right] at (450,1.4) {
        \begin{minipage}{8cm}
        \begin{enumerate}
                \item[(a)] $\sin{x\degree}=1$
                \item[(b)] $\sin{x\degree}=0$
                \item[(c)] $\sin{x\degree}=-1$
                \item[(d)] $\sin{x\degree}=0.6$
                \item[(e)] $\sin{x\degree}=-0.6$
                \item[(f)] $\sin{x\degree}=1.1$
        \end{enumerate}
        \end{minipage}
        };
    \end{tikzpicture}
\end{center}
    \item Use the graph of $y=\cos{x\degree}$ below to solve the following equations for $0\leqslant x \leqslant 360$.
    \begin{center}
    \begin{tikzpicture}[xscale=0.025,yscale=2]
        \draw[-stealth] (0,0) -- (380,0) node[right] {$x$};
        \draw[-stealth] (0,-1) -- (0,1.2) node[above] {$y$};
        \foreach \x in {0,30,...,360}{
        \draw (\x,0) -- (\x,-0.01);
        }
        \foreach \x in {90,180,270,360}{
        \node[below] at (\x,0) {$\small{\x}$};
        }
        \node[left] at (0,1.05) {1};
        \node[left] at (0,0.85) {0.9};
        \node[left] at (0,0) {0};
        \node[left] at (0,-1) {-1};
        \node[below] at (25.8,0) {$25.8$};
        \draw[thick,smooth,domain=0:360] plot (\x,{cos(\x)});
        \node[above] at (90,0.7) {$y=\cos{x}\degree$};
        \draw[dashed] (0,0.9) -- (25.8,0.9) -- (25.8,0);
        \draw[fill] (25.8,0.9) ellipse (1.5 and 0.01875);
        \node[below right] at (450,1.4) {
        \begin{minipage}{8cm}
        \begin{enumerate}
                \item[(a)] $\cos{x\degree}=1$
                \item[(b)] $\cos{x\degree}=0$
                \item[(c)] $\cos{x\degree}=-1$
                \item[(d)] $\cos{x\degree}=0.9$
                \item[(e)] $\cos{x\degree}=-0.9$
                \item[(f)] $\cos{x\degree}=1.1$
        \end{enumerate}
        \end{minipage}
        };
    \end{tikzpicture}
\end{center}
    \item Use the graph of $y=\tan{x\degree}$ below to solve the following equations for $0\leqslant x \leqslant 360$.
    \begin{center}
    \begin{tikzpicture}[xscale=0.025,yscale=0.4]
        \draw[-stealth] (0,0) -- (380,0) node[right] {$x$};
        \draw[-stealth] (0,-6) -- (0,6.5) node[above] {$y$};
        \foreach \x in {0,30,...,360}{
        \draw (\x,0) -- (\x,-0.01);
        }
        \foreach \x in {90,180,270,360}{
        \node[below] at (\x,0) {$\small{\x}$};
        }
        \node[left] at (0,6) {6};
        \node[left] at (0,1) {1};
        \node[left] at (0,0) {0};
        \node[left] at (0,-6) {-6};
        \node[below] at (45,0) {$45$};
        \draw[thick,smooth,domain=0:80] plot (\x,{tan(\x)});
        \draw[thick,smooth,domain=100:260] plot (\x,{tan(\x)});
        \draw[thick,smooth,domain=280:360] plot (\x,{tan(\x)});
        \draw[dashed] (90,-6) -- (90,6);
        \draw[dashed] (270,-6) -- (270,6);
        \node[left] at (260,6) {$y=\tan{x}\degree$};
        \draw[dashed] (0,1) -- (45,1) -- (45,0);
        \draw[fill] (45,1) ellipse (1.5 and 4*0.01875);
        \node[below right] at (450,6.6) {
        \begin{minipage}{8cm}
        \begin{enumerate}
                \item[(a)] $\tan{x\degree}=1$
                \item[(b)] $\tan{x\degree}=0$
                \item[(c)] $\tan{x\degree}=-1$
                \item[(d)] $\tan{x\degree}=3$
                \item[(e)] $\tan{x\degree}=-3$
                \item[(f)] $\tan{x\degree}=17$
        \end{enumerate}
        \end{minipage}
        };
    \end{tikzpicture}
\end{center}
    \item Given that $\sin^{-1}\left(\frac{1}{3}\right)=19.5\degree$, to one decimal place, solve $\sin{x\degree}=\frac{1}{3}$ for $0\leqslant x \leqslant 360$.
    \item Given that $\cos^{-1}\left(\frac{3}{4}\right)=41.4\degree$, to one decimal place, solve $4\cos{x\degree}=3$ for $0\leqslant x \leqslant 360$.
    \item Given that $\sin^{-1}\left(\frac{2}{3}\right)=41.8\degree$, to one decimal place, solve $3\sin{x\degree}+2=0$ for $0\leqslant x \leqslant 360$.
    \item Solve $5\cos{x\degree}+3=0$ for $0\leqslant x \leqslant 720$.
\end{enumerate}

\pagebreak

## Using the ASTC Diagram

\newpage

### Exercise 23.2 {-}

\newpage

## Points of Intersection

\newpage

### Exercise 23.3 {-}

\newpage

## Trig Functions in Context

\newpage

### Exercise 23.4 {-}

\newpage

## Trig Identities

\newpage

### Exercise 23.5 {-}

\newpage

## Review Exercise {-}
